name: Build & Test Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Print Folder Structure
      run: |
        echo "Current Directory:"
        pwd
        echo "List:"
        ls -R .

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Employee Portal
      working-directory: ./employeeportal
      run: mvn -B clean package

    - name: Build Notification Service
      working-directory: ./notificationservice
      run: mvn -B clean package

    - name: Build Payroll Service
      working-directory: ./payrollservice
      run: mvn -B clean package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jars
        path: |
          employeeportal/target/*.jar
          notificationservice/target/*.jar
          payrollservice/target/*.jar
